# Generated by Django 5.2.17 on 2026-10-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phoneotp_user_notify_daily_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=120, unique=True)),
                ('kind', models.CharField(max_length=5)),
                ('name', models.CharField(blank=True, max_length=80)),
                ('source', models.CharField(blank=True, max_length=40)),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'waitlist',
                'ordering': ['created_at'],
            },
        ),
    ]
