# Generated by Django 5.2.17 on 2026-10-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notify_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kyc_message',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_tier',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='paystack_customer_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('bvn_pending', 'Bvn Pending'), ('nin_verified', 'Nin Verified'), ('doc_uploaded', 'Doc Uploaded'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('needs_review', 'Needs Review')], default='not_started', max_length=20),
        ),
    ]
