# Generated by Django 5.2.17 on 2026-10-03 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_live_kyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signup_landing',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='signup_source',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
