# Generated by Django 5.2.17 on 2026-10-04 01:00

from django.db import migrations, models


def themed_to_light(apps, schema_editor):
    # Light is the new default. Anyone still on the old default never chose a look, so they move with it.
    apps.get_model("accounts", "User").objects.filter(look="themed").update(look="light")



class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_signup_source'),
    ]

    operations = [
        migrations.RunPython(themed_to_light, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='look',
            field=models.CharField(default='light', max_length=10),
        ),
    ]
