# Generated by Django 5.2.17 on 2026-10-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxmessage',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'Whatsapp'), ('push', 'Push'), ('in_app', 'In App'), ('sms', 'Sms'), ('email', 'Email')], max_length=10),
        ),
    ]
