# Generated by Django 5.2.17 on 2026-10-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolvedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip_bank_code', models.CharField(max_length=10)),
                ('account_number', models.CharField(max_length=10)),
                ('account_name', models.CharField(max_length=120)),
                ('provider', models.CharField(max_length=20)),
                ('resolved_at', models.DateTimeField()),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('nip_bank_code', 'account_number'), name='resolved_account_unique')],
            },
        ),
    ]
