# Generated by Django 5.2.17 on 2026-10-01 17:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('is_self', models.BooleanField(default=False)),
                ('bank_name', models.CharField(max_length=80)),
                ('nip_bank_code', models.CharField(max_length=10)),
                ('cbn_bank_code', models.CharField(blank=True, max_length=10)),
                ('account_number', models.CharField(max_length=10)),
                ('verified_account_name', models.CharField(max_length=120)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('notify_whatsapp', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('emoji', models.CharField(default='💸', max_length=8)),
                ('tint', models.CharField(default='cobalt', max_length=12)),
                ('amount_kobo', models.BigIntegerField()),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('month_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('month_day_last', models.BooleanField(default=False)),
                ('time_local', models.CharField(max_length=5)),
                ('tz', models.CharField(default='Africa/Lagos', max_length=64)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('deleted', 'Deleted')], default='active', max_length=10)),
                ('priority_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('provider', models.CharField(default='liberty', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='drips.recipient')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_for', models.DateTimeField()),
                ('amount_kobo', models.BigIntegerField()),
                ('fee_kobo', models.BigIntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('reserved', 'Reserved'), ('pending', 'Pending'), ('unknown', 'Unknown'), ('successful', 'Successful'), ('failed', 'Failed'), ('skipped_protected', 'Skipped Protected'), ('skipped_insufficient', 'Skipped Insufficient'), ('skipped_cap', 'Skipped Cap'), ('skipped_paused', 'Skipped Paused'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=24)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('provider_ref', models.CharField(blank=True, max_length=120)),
                ('provider_session_id', models.CharField(blank=True, max_length=120)),
                ('last_error', models.TextField(blank=True)),
                ('needs_review', models.BooleanField(default=False)),
                ('next_check_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='drips.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='recipient',
            constraint=models.UniqueConstraint(fields=('user', 'nip_bank_code', 'account_number'), name='recipient_unique_account'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(condition=models.Q(('priority_rank__isnull', False)), fields=('user', 'priority_rank'), name='plan_unique_priority_per_user'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('priority_rank__isnull', True), models.Q(('priority_rank__gte', 1), ('priority_rank__lte', 3)), _connector='OR'), name='plan_priority_1_to_3'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.CheckConstraint(condition=models.Q(('amount_kobo__gt', 0)), name='plan_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['status', 'scheduled_for'], name='drips_run_status_0c5783_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['status', 'next_check_at'], name='drips_run_status_f05b14_idx'),
        ),
        migrations.AddConstraint(
            model_name='run',
            constraint=models.UniqueConstraint(fields=('plan', 'scheduled_for'), name='run_unique_per_plan_time'),
        ),
    ]
