# Generated by Django 5.2.17 on 2026-10-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
