# Generated by Django 5.2.17 on 2026-10-02 12:33

from django.db import migrations, models


def itemise_scheduled(apps, schema_editor):
    """Old runs had a flat fee. Runs already settled keep it (as SpenDrip's fee); runs not yet sent get the new itemised fee."""
    from drips.services import fee_schedule
    Run = apps.get_model("drips", "Run")
    sched = fee_schedule()
    for r in Run.objects.all().only("id", "status", "amount_kobo", "fee_kobo"):
        if r.status == "scheduled":
            f = sched.parts(r.amount_kobo)
            r.fee_kobo, r.service_fee_kobo, r.provider_fee_kobo, r.stamp_duty_kobo = f.total_kobo, f.service_kobo, f.provider_kobo, f.stamp_duty_kobo
        else:
            r.service_fee_kobo, r.provider_fee_kobo, r.stamp_duty_kobo = r.fee_kobo, 0, 0
        r.save(update_fields=["fee_kobo", "service_fee_kobo", "provider_fee_kobo", "stamp_duty_kobo"])


class Migration(migrations.Migration):

    dependencies = [
        ('drips', '0002_recipient_paystack_recipient_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='provider_fee_kobo',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='run',
            name='service_fee_kobo',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='run',
            name='stamp_duty_kobo',
            field=models.BigIntegerField(default=0),
        ),
        migrations.RunPython(itemise_scheduled, migrations.RunPython.noop),
    ]
