# Generated by Django 5.2.17 on 2026-10-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drips', '0003_itemised_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duration_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='end_mode',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('months', 'Months'), ('date', 'Date')], default='ongoing', max_length=8),
        ),
        migrations.AddField(
            model_name='plan',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('finished', 'Finished'), ('deleted', 'Deleted')], default='active', max_length=10),
        ),
    ]
