# Generated by Django 5.2.17 on 2026-10-03 14:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drips', '0004_plan_start_end'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_kobo', models.BigIntegerField()),
                ('next_amount_kobo', models.BigIntegerField(blank=True, null=True)),
                ('skip_next', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RunBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('waiting', 'Waiting'), ('sending', 'Sending'), ('done', 'Done'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10)),
                ('amount_kobo', models.BigIntegerField(default=0)),
                ('fee_kobo', models.BigIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=40)),
                ('short_by_kobo', models.BigIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='run',
            name='run_unique_per_plan_time',
        ),
        migrations.AddField(
            model_name='plan',
            name='kind',
            field=models.CharField(choices=[('single', 'Single'), ('group', 'Group')], default='single', max_length=8),
        ),
        migrations.AlterField(
            model_name='plan',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='drips.recipient'),
        ),
        migrations.AddField(
            model_name='planline',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='drips.plan'),
        ),
        migrations.AddField(
            model_name='planline',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_lines', to='drips.recipient'),
        ),
        migrations.AddField(
            model_name='run',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='drips.planline'),
        ),
        migrations.AddField(
            model_name='runbatch',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='drips.plan'),
        ),
        migrations.AddField(
            model_name='runbatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='run',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='drips.runbatch'),
        ),
        migrations.AddConstraint(
            model_name='run',
            constraint=models.UniqueConstraint(condition=models.Q(('line__isnull', True)), fields=('plan', 'scheduled_for'), name='run_unique_per_plan_time'),
        ),
        migrations.AddConstraint(
            model_name='run',
            constraint=models.UniqueConstraint(condition=models.Q(('line__isnull', False)), fields=('line', 'scheduled_for'), name='run_unique_per_line_time'),
        ),
        migrations.AddConstraint(
            model_name='planline',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('plan', 'recipient'), name='planline_one_per_person'),
        ),
        migrations.AddConstraint(
            model_name='planline',
            constraint=models.CheckConstraint(condition=models.Q(('amount_kobo__gt', 0)), name='planline_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='runbatch',
            index=models.Index(fields=['status', 'scheduled_for'], name='drips_runba_status_1e11ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='runbatch',
            constraint=models.UniqueConstraint(fields=('plan', 'scheduled_for'), name='batch_unique_per_plan_time'),
        ),
    ]
