# Generated by Django 5.2.17 on 2026-10-03 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drips', '0005_group_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='runbatch',
            name='retry_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retry', to='drips.runbatch'),
        ),
    ]
