# Generated by Django 5.2.17 on 2026-10-06 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drips', '0006_payout_retry'),
        ('ledger', '0005_autofill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('payday_end', models.BooleanField(default=True)),
                ('payday_start', models.BooleanField(default=False)),
                ('just_in_time', models.BooleanField(default=True)),
                ('max_per_charge_kobo', models.BigIntegerField()),
                ('max_per_month_kobo', models.BigIntegerField()),
                ('paused_reason', models.CharField(blank=True, max_length=24)),
                ('failed_windows', models.PositiveSmallIntegerField(default=0)),
                ('skip_window', models.CharField(blank=True, max_length=16)),
                ('heads_up_window', models.CharField(blank=True, max_length=16)),
                ('heads_up_at', models.DateTimeField(blank=True, null=True)),
                ('consent_text', models.TextField(blank=True)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ledger.savedcard')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='autofill', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AutoFillAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('payday', 'Payday'), ('jit', 'Just In Time')], max_length=8)),
                ('key', models.CharField(max_length=80)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('amount_kobo', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('not_needed', 'Not Needed')], max_length=12)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ledger.cardcharge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autofill_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'at'], name='drips_autof_user_id_3869b7_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'kind', 'key', 'attempt'), name='autofill_attempt_once')],
            },
        ),
    ]
