# Generated by Django 5.2.17 on 2026-10-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfit', models.CharField(choices=[('xmas', 'Christmas: Santa hat'), ('newyear', 'New Year: party hat'), ('love', "Valentine's: heart boppers"), ('mama', 'Mothering Sunday: gele'), ('sallah', 'Sallah (Eid): kufi cap'), ('easter', 'Easter: bunny ears'), ('naija', 'Independence Day: flag and rosette'), ('halloween', 'Halloween (US): witch hat'), ('thanksgiving', 'Thanksgiving (US): knitted beanie'), ('stpatrick', "St Patrick's Day (US): green top hat"), ('usmom', "Mother's Day (US): flower crown"), ('juneteenth', 'Juneteenth (US): Juneteenth flag'), ('july4', 'Fourth of July (US): stars-and-stripes hat')], max_length=20)),
                ('name', models.CharField(blank=True, help_text='Optional, e.g. “Christmas 2026”. Shown only here.', max_length=60)),
                ('starts_on', models.DateField(help_text='First day Kobo wears it (Lagos time).')),
                ('ends_on', models.DateField(help_text='Last day Kobo wears it, inclusive.')),
                ('active', models.BooleanField(default=True, help_text='Untick to switch it off without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-starts_on'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='season_ends_after_start')],
            },
        ),
    ]
