# Generated by Django 5.2.17 on 2026-10-01 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='paystack', max_length=20)),
                ('authorization_code_enc', models.TextField()),
                ('signature', models.CharField(max_length=120)),
                ('brand', models.CharField(blank=True, max_length=20)),
                ('last4', models.CharField(max_length=4)),
                ('bank', models.CharField(blank=True, max_length=80)),
                ('exp_month', models.CharField(blank=True, max_length=2)),
                ('exp_year', models.CharField(blank=True, max_length=4)),
                ('email', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64, unique=True)),
                ('net_kobo', models.BigIntegerField()),
                ('fee_kobo', models.BigIntegerField()),
                ('gross_kobo', models.BigIntegerField()),
                ('save_card', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('success', 'Success'), ('failed', 'Failed')], default='started', max_length=10)),
                ('message', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('inflow', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='card_charge', to='ledger.inflow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_charges', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charges', to='ledger.savedcard')),
            ],
        ),
        migrations.AddConstraint(
            model_name='savedcard',
            constraint=models.UniqueConstraint(fields=('user', 'signature'), name='card_unique_per_user'),
        ),
    ]
