# Generated by Django 5.2.17 on 2026-10-02 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill(apps, schema_editor):
    """Fee rows for what already happened: settled drips (their flat fee, posted to the 'fees' account) and card top-ups."""
    FeeLine = apps.get_model("ledger", "FeeLine")
    Txn = apps.get_model("ledger", "LedgerTransaction")
    CardCharge = apps.get_model("ledger", "CardCharge")
    for t in Txn.objects.filter(kind="settle", run__isnull=False).select_related("run"):
        r = t.run
        if r.fee_kobo and not FeeLine.objects.filter(run=r, kind="service").exists():
            FeeLine.objects.create(kind="service", paid_to="spendrip", amount_kobo=r.fee_kobo, user_id=r.user_id, run=r,
                                   ledger_transaction=t, account_code="fees", provider=r.provider, reference=r.provider_ref or str(r.pk))
    for c in CardCharge.objects.filter(status="success", fee_kobo__gt=0):
        if not FeeLine.objects.filter(card_charge=c, kind="card_processing").exists():
            FeeLine.objects.create(kind="card_processing", paid_to="provider", amount_kobo=c.fee_kobo, user_id=c.user_id, card_charge=c,
                                   ledger_transaction=Txn.objects.filter(idempotency_key=f"inflow:paystack:{c.reference}").first(),
                                   provider="paystack", reference=c.reference)


class Migration(migrations.Migration):

    dependencies = [
        ('drips', '0003_itemised_fees'),
        ('ledger', '0002_savedcard_cardcharge_savedcard_card_unique_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('service', 'SpenDrip fee'), ('provider', 'Transfer fee (Paystack)'), ('stamp_duty', 'Stamp duty'), ('card_processing', 'Card fee (Paystack)')], max_length=20)),
                ('paid_to', models.CharField(choices=[('spendrip', 'SpenDrip (income)'), ('provider', 'Payment provider'), ('government', 'Government (FIRS)')], max_length=12)),
                ('amount_kobo', models.BigIntegerField()),
                ('account_code', models.CharField(blank=True, max_length=80)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card_charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_lines', to='ledger.cardcharge')),
                ('ledger_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_lines', to='ledger.ledgertransaction')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_lines', to='drips.run')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_lines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'indexes': [models.Index(fields=['kind', 'created_at'], name='ledger_feel_kind_d8aecd_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('run__isnull', False)), fields=('run', 'kind'), name='fee_once_per_run_kind'), models.UniqueConstraint(condition=models.Q(('card_charge__isnull', False)), fields=('card_charge', 'kind'), name='fee_once_per_charge_kind')],
            },
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
