# Generated by Django 5.2.17 on 2026-10-02 12:59

from django.db import migrations, models


def replay(apps, schema_editor):
    """Walk the ledger in posting order and fill in each entry's balance before/after, and each account's running balance."""
    Entry = apps.get_model("ledger", "LedgerEntry")
    Account = apps.get_model("ledger", "LedgerAccount")
    running, batch = {}, []
    for e in Entry.objects.order_by("transaction__created_at", "transaction_id", "id").only("id", "account_id", "amount_kobo"):
        before = running.get(e.account_id, 0)
        running[e.account_id] = before + e.amount_kobo
        e.balance_before_kobo, e.balance_after_kobo = before, running[e.account_id]
        batch.append(e)
    Entry.objects.bulk_update(batch, ["balance_before_kobo", "balance_after_kobo"], batch_size=1000)
    for account_id, bal in running.items():
        Account.objects.filter(pk=account_id).update(balance_kobo=bal)


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_itemised_fees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'verbose_name_plural': 'ledger entries'},
        ),
        migrations.AddField(
            model_name='ledgeraccount',
            name='balance_kobo',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='balance_after_kobo',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='balance_before_kobo',
            field=models.BigIntegerField(null=True),
        ),
        migrations.RunPython(replay, migrations.RunPython.noop),
    ]
