# Generated by Django 5.2.17 on 2026-10-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_running_balances'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcharge',
            name='source',
            field=models.CharField(default='manual', max_length=10),
        ),
    ]
